version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: estampaider-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  config-server:
    build:
      context: ./config-server
    container_name: config-server
    ports:
      - "8089:8089"
    depends_on:
      - mongo
    environment:
      - SPRING_PROFILES_ACTIVE=default

  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=default

  usuarios-servicio:
    build:
      context: ./usuarios-servicio
    container_name: usuarios-servicio
    ports:
      - "8081:8081"
    depends_on:
      - mongo
      - eureka-server
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - spring.data.mongodb.uri=mongodb://mongo:27017/estampaider
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

  productos-servicio:
    build:
      context: ./productos-servicio
    container_name: productos-servicio
    ports:
      - "8082:8082"
    depends_on:
      - mongo
      - eureka-server
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - spring.data.mongodb.uri=mongodb://mongo:27017/estampaider
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

  pedidos-servicio:
    build:
      context: ./pedidos-servicio
    container_name: pedidos-servicio
    ports:
      - "8083:8083"
    depends_on:
      - mongo
      - eureka-server
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

  gateway-servicio:
    build:
      context: ./gateway-servicio
    container_name: gateway-servicio
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

  estampaider-web:
    build:
      context: ./estampaider-web
    container_name: estampaider-web
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - spring.data.mongodb.uri=mongodb://mongo:27017/estampaider
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - usuarios-servicio
      - productos-servicio
      - pedidos-servicio
      - gateway-servicio

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  mongo-data:

  

