server:
  port: 8089  

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Jaico98/config-estampaider
          default-label: main
          clone-on-start: true
