name: Despliegue Estampaider

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v4

    - name: Instalar Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose -y

    - name: Dar permisos de ejecución
      run: chmod +x ./mvnw || true

    - name: Construir imágenes con Docker Compose
      run: docker-compose build

    - name: Levantar microservicios
      run: docker-compose up -d

    - name: Verificar contenedores activos
      run: docker ps

    - name: Ver logs (usuarios-servicio)
      run: docker logs usuarios-servicio || true
